"""
Knowledge Graph Data — Grade 7 Mathematics (人教版)
===================================================

Structured curriculum data for the Socratic tutoring system.
This covers the complete Grade 7 (七年级) math curriculum.
"""

from __future__ import annotations

from deeptutor.k12.models import KnowledgePoint, KnowledgeGraph, Semester, Textbook


def build_grade7_graph() -> KnowledgeGraph:
    """Build the complete Grade 7 math knowledge graph (人教版)."""
    points = [
        # ─── 七年级上册 第1章：有理数 ───────────────────────────────────
        KnowledgePoint(
            id="rational_number_concept",
            name="有理数的概念",
            name_en="Concept of Rational Numbers",
            grade=7,
            semester=Semester.UP,
            chapter=1,
            section=1,
            prerequisites=[],
            difficulty=1,
            curriculum_requirement="理解",
            key_concepts=["正数", "负数", "整数", "分数", "有理数分类"],
            common_mistakes=["0既不是正数也不是负数容易忘记", "把无限不循环小数当作有理数"],
            tags=["数与代数", "基础概念"],
        ),
        KnowledgePoint(
            id="number_line",
            name="数轴",
            name_en="Number Line",
            grade=7,
            semester=Semester.UP,
            chapter=1,
            section=2,
            prerequisites=["rational_number_concept"],
            difficulty=1,
            curriculum_requirement="掌握",
            key_concepts=["原点", "正方向", "单位长度", "数轴三要素"],
            common_mistakes=["画数轴忘记箭头", "单位长度不均匀"],
            tags=["数与代数", "数形结合"],
        ),
        KnowledgePoint(
            id="opposite_number",
            name="相反数",
            name_en="Opposite Numbers",
            grade=7,
            semester=Semester.UP,
            chapter=1,
            section=3,
            prerequisites=["number_line"],
            difficulty=1,
            curriculum_requirement="掌握",
            key_concepts=["互为相反数", "0的相反数是0", "数轴上关于原点对称"],
            common_mistakes=["忘记0的相反数是0"],
            tags=["数与代数"],
        ),
        KnowledgePoint(
            id="absolute_value",
            name="绝对值",
            name_en="Absolute Value",
            grade=7,
            semester=Semester.UP,
            chapter=1,
            section=4,
            prerequisites=["number_line", "opposite_number"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["几何意义：到原点的距离", "代数意义：分类讨论", "|a|≥0"],
            common_mistakes=["负数的绝对值忘记去掉负号", "含绝对值的方程忘记分类讨论"],
            tags=["数与代数"],
        ),
        KnowledgePoint(
            id="rational_addition_subtraction",
            name="有理数的加减法",
            name_en="Addition and Subtraction of Rational Numbers",
            grade=7,
            semester=Semester.UP,
            chapter=1,
            section=5,
            prerequisites=["absolute_value", "opposite_number"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["同号相加", "异号相加", "加法交换律", "加法结合律", "减法转加法"],
            common_mistakes=["异号相加时符号判断错误", "减法转加法时忘记变号"],
            tags=["数与代数", "运算"],
        ),
        KnowledgePoint(
            id="rational_multiplication_division",
            name="有理数的乘除法",
            name_en="Multiplication and Division of Rational Numbers",
            grade=7,
            semester=Semester.UP,
            chapter=1,
            section=6,
            prerequisites=["rational_addition_subtraction"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["符号法则", "倒数", "乘法分配律", "除法转乘法"],
            common_mistakes=["多个负数相乘时符号判断错误", "0不能做除数"],
            tags=["数与代数", "运算"],
        ),
        KnowledgePoint(
            id="rational_power",
            name="有理数的乘方",
            name_en="Powers of Rational Numbers",
            grade=7,
            semester=Semester.UP,
            chapter=1,
            section=7,
            prerequisites=["rational_multiplication_division"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["底数", "指数", "幂", "负数的奇数次幂为负", "负数的偶数次幂为正"],
            common_mistakes=["(-2)²和-2²混淆", "底数为负数时忘记加括号"],
            tags=["数与代数", "运算"],
        ),
        KnowledgePoint(
            id="mixed_operations",
            name="有理数的混合运算",
            name_en="Mixed Operations with Rational Numbers",
            grade=7,
            semester=Semester.UP,
            chapter=1,
            section=8,
            prerequisites=["rational_power", "rational_addition_subtraction"],
            difficulty=3,
            curriculum_requirement="掌握",
            key_concepts=["运算顺序：先乘方再乘除最后加减", "括号优先", "运算律简化计算"],
            common_mistakes=["运算顺序错误", "去括号时符号处理错误"],
            tags=["数与代数", "运算"],
        ),

        # ─── 七年级上册 第2章：整式的加减 ─────────────────────────────────
        KnowledgePoint(
            id="algebraic_expression",
            name="整式的概念",
            name_en="Algebraic Expressions",
            grade=7,
            semester=Semester.UP,
            chapter=2,
            section=1,
            prerequisites=["mixed_operations"],
            difficulty=2,
            curriculum_requirement="理解",
            key_concepts=["单项式", "多项式", "整式", "系数", "次数"],
            common_mistakes=["π是常数不是未知数", "单项式次数是所有字母指数之和"],
            tags=["数与代数", "代数式"],
        ),
        KnowledgePoint(
            id="like_terms",
            name="同类项与合并同类项",
            name_en="Like Terms and Combining Like Terms",
            grade=7,
            semester=Semester.UP,
            chapter=2,
            section=2,
            prerequisites=["algebraic_expression"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["同类项的定义", "合并同类项法则", "系数相加字母不变"],
            common_mistakes=["字母相同但指数不同误认为同类项", "合并时忘记处理符号"],
            tags=["数与代数", "代数式"],
        ),
        KnowledgePoint(
            id="remove_brackets",
            name="去括号与添括号",
            name_en="Removing and Adding Brackets",
            grade=7,
            semester=Semester.UP,
            chapter=2,
            section=3,
            prerequisites=["like_terms"],
            difficulty=3,
            curriculum_requirement="掌握",
            key_concepts=["括号前是+号各项不变", "括号前是-号各项变号", "分配律"],
            common_mistakes=["去括号时漏乘某一项", "括号前是负号时只变了第一项的符号"],
            tags=["数与代数", "代数式"],
        ),
        KnowledgePoint(
            id="polynomial_operations",
            name="整式的加减运算",
            name_en="Addition and Subtraction of Polynomials",
            grade=7,
            semester=Semester.UP,
            chapter=2,
            section=4,
            prerequisites=["remove_brackets", "like_terms"],
            difficulty=3,
            curriculum_requirement="掌握",
            key_concepts=["去括号", "合并同类项", "整式加减步骤"],
            common_mistakes=["去括号后忘记合并同类项", "减法时括号内各项未全部变号"],
            tags=["数与代数", "代数式", "运算"],
        ),

        # ─── 七年级上册 第3章：一元一次方程 ───────────────────────────────
        KnowledgePoint(
            id="equation_concept",
            name="方程与一元一次方程的概念",
            name_en="Equations and Linear Equations in One Variable",
            grade=7,
            semester=Semester.UP,
            chapter=3,
            section=1,
            prerequisites=["algebraic_expression"],
            difficulty=2,
            curriculum_requirement="理解",
            key_concepts=["方程的定义", "一元一次方程的标准形式ax+b=0", "解的含义"],
            common_mistakes=["方程必须含等号和未知数", "混淆方程和等式"],
            tags=["数与代数", "方程"],
        ),
        KnowledgePoint(
            id="equation_properties",
            name="等式的性质",
            name_en="Properties of Equations",
            grade=7,
            semester=Semester.UP,
            chapter=3,
            section=2,
            prerequisites=["equation_concept"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["等式两边同加同减", "等式两边同乘同除（除数不为0）"],
            common_mistakes=["两边同除时忘记除数不能为0"],
            tags=["数与代数", "方程"],
        ),
        KnowledgePoint(
            id="solve_linear_equation",
            name="解一元一次方程",
            name_en="Solving Linear Equations in One Variable",
            grade=7,
            semester=Semester.UP,
            chapter=3,
            section=3,
            prerequisites=["equation_properties", "polynomial_operations"],
            difficulty=3,
            curriculum_requirement="掌握",
            key_concepts=["去分母", "去括号", "移项", "合并同类项", "系数化为1"],
            common_mistakes=["移项不变号", "去分母时漏乘某一项", "去括号时分配律出错"],
            tags=["数与代数", "方程", "核心技能"],
        ),
        KnowledgePoint(
            id="equation_word_problems",
            name="一元一次方程应用题",
            name_en="Word Problems with Linear Equations",
            grade=7,
            semester=Semester.UP,
            chapter=3,
            section=4,
            prerequisites=["solve_linear_equation"],
            difficulty=4,
            curriculum_requirement="掌握",
            key_concepts=["设未知数", "找等量关系", "列方程", "解方程", "检验"],
            common_mistakes=["找不到等量关系", "设未知数不当", "忘记检验答案合理性"],
            tags=["数与代数", "方程", "应用"],
        ),

        # ─── 七年级上册 第4章：几何图形初步 ───────────────────────────────
        KnowledgePoint(
            id="geometric_figures_basic",
            name="几何图形基本概念",
            name_en="Basic Geometric Figures",
            grade=7,
            semester=Semester.UP,
            chapter=4,
            section=1,
            prerequisites=[],
            difficulty=1,
            curriculum_requirement="了解",
            key_concepts=["点", "线", "面", "体", "立体图形", "平面图形"],
            common_mistakes=["线段和射线混淆"],
            tags=["图形与几何", "基础概念"],
        ),
        KnowledgePoint(
            id="line_segment_ray",
            name="直线、射线、线段",
            name_en="Lines, Rays, and Line Segments",
            grade=7,
            semester=Semester.UP,
            chapter=4,
            section=2,
            prerequisites=["geometric_figures_basic"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["两点确定一条直线", "线段中点", "两点之间线段最短"],
            common_mistakes=["射线有一个端点而直线没有端点", "线段可以度量长度"],
            tags=["图形与几何"],
        ),
        KnowledgePoint(
            id="angle_concept",
            name="角",
            name_en="Angles",
            grade=7,
            semester=Semester.UP,
            chapter=4,
            section=3,
            prerequisites=["line_segment_ray"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["角的定义", "角的度量", "角的分类", "角平分线", "互补互余"],
            common_mistakes=["互补和互余混淆", "角平分线的性质记错"],
            tags=["图形与几何"],
        ),

        # ─── 七年级下册 第5章：相交线与平行线 ─────────────────────────────
        KnowledgePoint(
            id="intersecting_lines",
            name="相交线",
            name_en="Intersecting Lines",
            grade=7,
            semester=Semester.DOWN,
            chapter=5,
            section=1,
            prerequisites=["angle_concept"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["对顶角相等", "邻补角互补", "垂线", "点到直线的距离"],
            common_mistakes=["对顶角和邻补角混淆", "垂线段最短而非垂线最短"],
            tags=["图形与几何"],
        ),
        KnowledgePoint(
            id="parallel_lines",
            name="平行线",
            name_en="Parallel Lines",
            grade=7,
            semester=Semester.DOWN,
            chapter=5,
            section=2,
            prerequisites=["intersecting_lines"],
            difficulty=3,
            curriculum_requirement="掌握",
            key_concepts=["平行线的判定", "平行线的性质", "同位角", "内错角", "同旁内角"],
            common_mistakes=["判定和性质混淆", "三线八角找错对应角"],
            tags=["图形与几何", "推理"],
        ),

        # ─── 七年级下册 第6章：实数 ───────────────────────────────────────
        KnowledgePoint(
            id="square_root",
            name="平方根与算术平方根",
            name_en="Square Roots",
            grade=7,
            semester=Semester.DOWN,
            chapter=6,
            section=1,
            prerequisites=["rational_power"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["平方根", "算术平方根", "开方运算", "被开方数≥0"],
            common_mistakes=["平方根有正负两个而算术平方根只取正值", "负数没有平方根"],
            tags=["数与代数"],
        ),
        KnowledgePoint(
            id="cube_root",
            name="立方根",
            name_en="Cube Roots",
            grade=7,
            semester=Semester.DOWN,
            chapter=6,
            section=2,
            prerequisites=["square_root"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["立方根", "任何数都有唯一立方根", "负数也有立方根"],
            common_mistakes=["和平方根混淆：立方根只有一个"],
            tags=["数与代数"],
        ),
        KnowledgePoint(
            id="real_numbers",
            name="实数",
            name_en="Real Numbers",
            grade=7,
            semester=Semester.DOWN,
            chapter=6,
            section=3,
            prerequisites=["square_root", "cube_root"],
            difficulty=3,
            curriculum_requirement="理解",
            key_concepts=["无理数", "实数分类", "实数与数轴一一对应"],
            common_mistakes=["π是无理数", "无限不循环小数才是无理数"],
            tags=["数与代数"],
        ),

        # ─── 七年级下册 第7章：平面直角坐标系 ─────────────────────────────
        KnowledgePoint(
            id="coordinate_system",
            name="平面直角坐标系",
            name_en="Cartesian Coordinate System",
            grade=7,
            semester=Semester.DOWN,
            chapter=7,
            section=1,
            prerequisites=["number_line", "real_numbers"],
            difficulty=2,
            curriculum_requirement="掌握",
            key_concepts=["x轴y轴", "原点", "象限", "坐标", "有序数对"],
            common_mistakes=["坐标轴上的点不属于任何象限", "x和y坐标写反"],
            tags=["数与代数", "数形结合"],
        ),
        KnowledgePoint(
            id="coordinate_geometry",
            name="坐标方法的简单应用",
            name_en="Applications of Coordinates",
            grade=7,
            semester=Semester.DOWN,
            chapter=7,
            section=2,
            prerequisites=["coordinate_system"],
            difficulty=3,
            curriculum_requirement="掌握",
            key_concepts=["用坐标表示位置", "用坐标表示平移"],
            common_mistakes=["平移时搞混x和y方向的变化"],
            tags=["数与代数", "数形结合", "应用"],
        ),

        # ─── 七年级下册 第8章：二元一次方程组 ─────────────────────────────
        KnowledgePoint(
            id="system_of_equations_concept",
            name="二元一次方程组的概念",
            name_en="Systems of Linear Equations in Two Variables",
            grade=7,
            semester=Semester.DOWN,
            chapter=8,
            section=1,
            prerequisites=["solve_linear_equation"],
            difficulty=2,
            curriculum_requirement="理解",
            key_concepts=["二元一次方程", "方程组", "方程组的解"],
            common_mistakes=["解必须同时满足两个方程"],
            tags=["数与代数", "方程"],
        ),
        KnowledgePoint(
            id="substitution_method",
            name="代入消元法",
            name_en="Substitution Method",
            grade=7,
            semester=Semester.DOWN,
            chapter=8,
            section=2,
            prerequisites=["system_of_equations_concept"],
            difficulty=3,
            curriculum_requirement="掌握",
            key_concepts=["用一个方程表示一个未知数", "代入另一个方程", "消元"],
            common_mistakes=["代入时忘记加括号", "代入后化简出错"],
            tags=["数与代数", "方程", "核心技能"],
        ),
        KnowledgePoint(
            id="elimination_method",
            name="加减消元法",
            name_en="Elimination Method",
            grade=7,
            semester=Semester.DOWN,
            chapter=8,
            section=3,
            prerequisites=["system_of_equations_concept"],
            difficulty=3,
            curriculum_requirement="掌握",
            key_concepts=["系数相同或相反时直接加减", "需要先变形再加减"],
            common_mistakes=["加减时忘记对齐同一未知数", "变形后符号出错"],
            tags=["数与代数", "方程", "核心技能"],
        ),
        KnowledgePoint(
            id="system_word_problems",
            name="二元一次方程组应用题",
            name_en="Word Problems with Systems of Equations",
            grade=7,
            semester=Semester.DOWN,
            chapter=8,
            section=4,
            prerequisites=["substitution_method", "elimination_method"],
            difficulty=4,
            curriculum_requirement="掌握",
            key_concepts=["设两个未知数", "找两个等量关系", "列方程组"],
            common_mistakes=["只找到一个等量关系", "设未知数时单位不统一"],
            tags=["数与代数", "方程", "应用"],
        ),

        # ─── 七年级下册 第9章：不等式与不等式组 ───────────────────────────
        KnowledgePoint(
            id="inequality_concept",
            name="不等式的概念与性质",
            name_en="Inequalities: Concepts and Properties",
            grade=7,
            semester=Semester.DOWN,
            chapter=9,
            section=1,
            prerequisites=["solve_linear_equation"],
            difficulty=2,
            curriculum_requirement="理解",
            key_concepts=["不等式", "不等式的基本性质", "两边同乘负数要变号"],
            common_mistakes=["两边乘以负数时忘记变号"],
            tags=["数与代数", "不等式"],
        ),
        KnowledgePoint(
            id="solve_linear_inequality",
            name="解一元一次不等式",
            name_en="Solving Linear Inequalities",
            grade=7,
            semester=Semester.DOWN,
            chapter=9,
            section=2,
            prerequisites=["inequality_concept", "solve_linear_equation"],
            difficulty=3,
            curriculum_requirement="掌握",
            key_concepts=["解不等式步骤同方程", "系数化为1时注意正负", "解集在数轴上表示"],
            common_mistakes=["系数为负数除过去忘记变号", "数轴表示时实心空心搞混"],
            tags=["数与代数", "不等式", "核心技能"],
        ),
        KnowledgePoint(
            id="inequality_group",
            name="一元一次不等式组",
            name_en="Systems of Linear Inequalities",
            grade=7,
            semester=Semester.DOWN,
            chapter=9,
            section=3,
            prerequisites=["solve_linear_inequality"],
            difficulty=3,
            curriculum_requirement="掌握",
            key_concepts=["不等式组的解集", "同大取大", "同小取小", "大小小大取中间", "大大小小无解"],
            common_mistakes=["取交集时方向搞错", "口诀记混"],
            tags=["数与代数", "不等式"],
        ),

        # ─── 七年级下册 第10章：数据的收集与整理 ──────────────────────────
        KnowledgePoint(
            id="data_collection",
            name="数据的收集、整理与描述",
            name_en="Data Collection and Organization",
            grade=7,
            semester=Semester.DOWN,
            chapter=10,
            section=1,
            prerequisites=[],
            difficulty=1,
            curriculum_requirement="了解",
            key_concepts=["全面调查", "抽样调查", "频率", "频数", "统计图表"],
            common_mistakes=["频率和频数混淆", "样本代表性不足"],
            tags=["统计与概率"],
        ),
    ]

    return KnowledgeGraph(
        subject="math",
        grade=7,
        textbook=Textbook.RENJIAOBAN,
        points=points,
    )


# Convenience accessor
GRADE_7_MATH = build_grade7_graph()
